openapi: 3.0.1
info:
  title: arXiv Xplorer
  description: A plugin that does semantic search over arXiv papers.
  version: 'v1'
servers:
  - url: http://localhost:5003
paths:
  /xplorer/{query}:
    get:
      operationId: searchArxiv
      summary: Search for arXiv papers using a text query.
      parameters:
      - in: path
        name: query
        schema:
            type: string
        required: true
        description: The search query.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/searchArxivResponse'
  /xplorer-similarity/{id}:
    get:
      operationId: similaritySearchArxiv
      summary: Search for arXiv papers by similarity to another arXiv paper.
      parameters:
      - in: path
        name: id
        schema:
            type: string
        required: true
        description: The paper's ID.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/searchArxivResponse'

components:
  schemas:
    searchArxivResponse:
      type: object
      properties:
        papers:
          type: array
          description: The list of most similar papers.
          items:
            type: object
            properties:
              id:
                type: string
                description: The arXiv paper's ID.
              title:
                type: string
                description: The arXiv paper's title.
              author:
                type: string
                description: The arXiv paper's author.
              score:
                type: number
                description: The semantic similarity of the paper.
              abstract:
                type: string
                description: The arXiv paper's abstract.
