info:
  description: Discover, read, reference, and search through all arXiv papers.
  title: arXiv Xplorer
  version: v1
openapi: 3.0.1
paths:
  /chunk_search:
    post:
      operationId: chunk_search
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              properties:
                count:
                  default: 3
                  description: The number of results to return.
                  type: integer
                page:
                  default: 1
                  description: Pagination index.
                  type: integer
                paper_id:
                  description: arxiv ID.
                  type: string
                query:
                  description: The user's query.
                  type: string
              required:
              - paper_id
              - query
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  type: string
                type: array
          description: A list of matching chunks in descending order of similarity.
      summary: Perform semantic search for a query across 250 word chunks of a paper's
        sections.
  /read_citation:
    post:
      operationId: read_citation
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              properties:
                citation:
                  description: The citation ID to lookup. e.g. `demo` from the citation
                    `<cit. demo>`
                  type: string
                paper_id:
                  description: arxiv ID.
                  type: string
              required:
              - paper_id
              - citation
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                type: string
          description: The citation text.
      summary: Lookup a particular citation id of a paper, if paper_metadata.can_read_citation
        == True.
  /read_paper_metadata:
    post:
      operationId: read_paper_metadata
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              properties:
                paper_id:
                  description: arxiv ID.
                  type: string
                show_abstract:
                  default: true
                  description: Include the abstract in the response.
                  type: boolean
              required:
              - paper_id
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  abstract:
                    type: string
                  authors:
                    type: string
                  can_read_citation:
                    type: boolean
                  date:
                    type: string
                  id:
                    type: string
                  table_of_contents:
                    type: string
                  title:
                    type: string
                type: object
          description: OK
      summary: 'Read the metadata of a paper, where available. Including the paper''s
        id, title, date, authors, abstract, table_of_contents, can_read_citation.'
  /read_section:
    post:
      operationId: read_section
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              properties:
                paper_id:
                  description: arxiv ID.
                  type: string
                section_id:
                  anyOf:
                  - type: integer
                  - items:
                      type: integer
                    type: array
                  description: 1-indexed section ID, or list of subsection ids.
              required:
              - paper_id
              - section_id
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                type: string
          description: Section title and content
      summary: Read a specific section from the table of contents of a paper.
  /search:
    post:
      operationId: search
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              properties:
                count:
                  default: 8
                  description: The number of results to return.
                  type: integer
                method:
                  default: semantic
                  description: The search method to use.
                  enum:
                  - keyword
                  - semantic
                  - similarity
                  type: string
                page:
                  default: 1
                  description: Pagination index.
                  type: integer
                query:
                  description: The user's query.
                  type: string
                year:
                  anyOf:
                  - type: integer
                  - type: 'null'
                  default: null
                  description: The year to filter results by. Defaults to None, for
                    any year.
              required:
              - query
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  properties:
                    abstract_snippet:
                      type: string
                    date:
                      type: string
                    first_author:
                      type: string
                    id:
                      type: string
                    title:
                      type: string
                  type: object
                type: array
          description: OK
      summary: 'Searches for arxiv articles using the user''s query.

        Semantic search is preferred unless you want an exact keyword, or you want
        an exact paper.

        Similarity search will find similar results given an arxiv paper ID or URL.'
